# ~/.alacritty.yml

shell:
  program: /bin/bash

window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: full
  opacity: 1.0
  decorations_theme_variant: Dark

font:
  normal:
    family: DaddyTimeMono Nerd Font
    style: Regular
  bold:
    family: DaddyTimeMono Nerd Font
    style: Bold
  italic:
    family: DaddyTimeMono Nerd Font
    style: Italic
  bold_italic:
    family: DaddyTimeMono Nerd Font
    style: Bold Italic
  size: 12.0
  offset:
    x: 1
    y: 5

selection:
  save_to_clipboard: true

