[font]
size = 12.0

[font.bold]
family = "DaddyTimeMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DaddyTimeMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DaddyTimeMono Nerd Font"
style = "Italic"

[font.normal]
family = "DaddyTimeMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 5

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/bash"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 5
y = 5

[terminal]
