[terminal.shell]
program = "/bin/bash"

[window]
padding = { x = 15, y = 15 }
dynamic_padding = true
decorations = "Full"
opacity = 0.95
decorations_theme_variant = "Dark"

[font]
normal = { family = "ComicShannsMono Nerd Font Mono", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font Mono", style = "Bold" }
italic = { family = "ComicShannsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "ComicShannsMono Nerd Font Mono", style = "Bold Italic" }
size = 12
offset = { x = 1, y = 5 }

[selection]
save_to_clipboard = true

[terminal]

